theme: jekyll-theme-cayman
title: Applied Linear Regression Models using R and Excel
description: "Feel free to bookmark this page to be able to use R and Excel for Applied Linear Regression Models. 
This page is maintained for learners of Applied Linear Regression Models to simply supplement their learning with ready to use 
Excel and R files. The goal here is not necessarily to explain statistical concepts or how R works, both of which 
are already well documented online." 
has_children: true
